[ROAD-804] fix: vs 2017 crash issue and update version
snyk/snyk-visual-studio-plugin pull request #112
Opened 2022-04-01 07:37 UTC by aldanchenko

Add `System.Runtime.CompilerServices.Unsafe` dll to vsix file and add binding redirect for different versions of this assembly.

2022-04-04 07:21 UTC, michelkaporin reviewed
Let's start updating CHANGELOG.md manually when we fix/add/change something, as we do in other plugins. Otherwise LGTM 👌

2022-04-04 07:23 UTC, pavel-snyk approved these changes
@aldanchenko, LGTM.
p.s.: I re-run the failed build step (we had issues with deeproxy).

2022-04-04 07:52 UTC, aldanchenko commented
@michelkaporin added changelog file. Could you check it, please? Thanks!

2022-04-04 10:33 UTC, michelkaporin requested changes

2022-04-04 10:33 UTC, michelkaporin commented on Snyk.VisualStudio.Extension.2022/CHANGELOG.txt
> +﻿Snyk Changelog
It's not complete. Let's add everything that was added as part of 1.1.7 and please follow a format from other repos 🙏

2022-04-04 10:33 UTC, michelkaporin commented on Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
> +      <IncludeInVSIX>true</IncludeInVSIX>
Don't think we need to include it in VSIX, @asaf92 what do you think?

2022-04-04 10:34 UTC, michelkaporin commented on Snyk.VisualStudio.Extension.2022/CHANGELOG.txt
> +﻿Snyk Changelog
We should be then be updating CHANGELOG on every PR that's user facing as we do in IntelliJ repo :)

2022-04-04 10:38 UTC, aldanchenko commented on Snyk.VisualStudio.Extension.2022/CHANGELOG.txt
> +﻿Snyk Changelog
Yes, it's not complete for 2022. Because this changes related to 2015-2019 vs versions. And for this versions we have this file - https://github.com/snyk/snyk-visual-studio-plugin/blob/fix/vs2017-crash-issue/Snyk.VisualStudio.Extension/CHANGELOG.txt

And I don't sure VS support markdown. Because we could include in vsix only txt or html. But if we don't need to include this file to vsix we could switch and use markdown as for other IDEs

2022-04-04 12:49 UTC, asaf92 commented on Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
> +      <IncludeInVSIX>true</IncludeInVSIX>
Not sure.

It's included in the `<ReleaseNotes>` tag in the `vsixmanifest` file, but the MSDN docs aren't clear on whether we need to explicitly include it in the .csproj and add an `<IncludeInVSIX>true</IncludeInVSIX>`

2022-04-04 13:10 UTC, michelkaporin commented on Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
> +      <IncludeInVSIX>true</IncludeInVSIX>
@aldanchenko let's have it link to the GH page for easiness of tracking everything in a single .MD file for all versions. We shouldn't have a big differences between specific version changes anyway as this one should be an exception.

2022-04-04 13:13 UTC, aldanchenko commented on Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
> +      <IncludeInVSIX>true</IncludeInVSIX>
@michelkaporin great! One additional question: CHANGELOG.md in root of our repo (not in Snyk.VisualStudio.Extension or Snyk.VisualStudio.Extension.2022), right?

2022-04-04 13:15 UTC, michelkaporin commented on Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
> +      <IncludeInVSIX>true</IncludeInVSIX>
@aldanchenko yeah, that would be consistent :)

2022-04-04 14:31 UTC, michelkaporin commented on Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
> +        <ReleaseNotes >https://github.com/snyk/snyk-visual-studio-plugin/blob/main/CHANGELOG.md</ReleaseNotes>
Not working for me. Also is space a valid char in the opening xml tag? 👁️

2022-04-04 14:33 UTC, michelkaporin commented on snyk-visual-studio-plugin.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Snyk.Common.Tests", "Snyk.Common.Tests\Snyk.Common.Tests.csproj", "{F3FC7A42-F53F-4938-8D37-D1ABAF6A8A90}"
How come this has changed? 👀

2022-04-04 14:37 UTC, aldanchenko commented on snyk-visual-studio-plugin.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Snyk.Common.Tests", "Snyk.Common.Tests\Snyk.Common.Tests.csproj", "{F3FC7A42-F53F-4938-8D37-D1ABAF6A8A90}"
Visual Studio just surprises me. I just added new file to Solution

2022-04-04 14:53 UTC, aldanchenko commented on snyk-visual-studio-plugin.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Snyk.Common.Tests", "Snyk.Common.Tests\Snyk.Common.Tests.csproj", "{F3FC7A42-F53F-4938-8D37-D1ABAF6A8A90}"
@michelkaporin I don't sure I need to edit this file by my self without VS and VS made this changes

2022-04-05 08:11 UTC, asaf92 commented on snyk-visual-studio-plugin.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Snyk.Common.Tests", "Snyk.Common.Tests\Snyk.Common.Tests.csproj", "{F3FC7A42-F53F-4938-8D37-D1ABAF6A8A90}"
This change means that the project type has changed from .NET Framework to .NET Core.

Apparently this is a [known bug](https://developercommunity.visualstudio.com/t/project-guid-changes-when-building-in-vs2017-vs-bu/304031) in VS2017, but it could be related to the fact that a .NET Core DLL (CompilerServices.Unsafe) was added

2022-04-05 12:11 UTC, michelkaporin approved these changes
LGTM 👍 Happy to see it fixed and changelog rolling into the code 🥳

2022-04-06 06:29 UTC, michelkaporin approved these changes

2022-04-06 06:32 UTC, merged