[ROAD-314] Feat preview release
snyk/snyk-visual-studio-plugin pull request #39
Opened 2021-09-20 09:30 UTC by aldanchenko

Change version.
Fix few simple bugs.

2021-09-30 12:30 UTC, michelkaporin commented
@aldanchenko I'd love to review this PR but it seems not to be rebased. Please ping me when it's ready 🙌

2021-10-01 08:22 UTC, aldanchenko commented
@michelkaporin could you please check last changes? Thank you!

2021-10-01 09:42 UTC, michelkaporin commented
@aldanchenko sorry, but I see the same diff as in old PRs here. I see you do merges here instead of our typical git rebase workflow. Be careful, this could lead to problems when mixing both rebase and merge.

2021-10-01 17:45 UTC, aldanchenko commented
@michelkaporin I tried to fix it. How about now?

2021-10-04 07:40 UTC, michelkaporin requested changes

2021-10-04 07:40 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
Should we perhaps have another manifest next to the stable one with `Snyk.VisualStudio.Extension/source.extension.preview.vsixmanifest`. Such that every time we have to release preview, we can just rename the file.

Current way would mean we have to copy-paste all the information from the existing stable release which would take more time.

I'd love if we can automate all this by using PowerShell script as a post-build task. Can you look into that? Perhaps as another ticket at some point in future.

2021-10-04 07:40 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykExtension.cs
> +        public const string IntegrationName = "VISUAL_STUDIO_PREVIEW";
Can we pull this name from vsix the same way the version is pulled from? This will reduce amount of work to be checked off during the release process (i.e. answering the question is the integration name stable or preview for the release I am making?).

2021-10-04 07:40 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykService.cs
> +        public SnykApiService ApiService
Just verifying if this code has to be here. Feel free to mark as resolved, however doesn't seem to be related to the Preview release work.

2021-10-04 07:56 UTC, aldanchenko commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
I'll take a look

2021-10-04 08:09 UTC, aldanchenko commented on Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykExtension.cs
> +        public const string IntegrationName = "VISUAL_STUDIO_PREVIEW";
Good point! It seems we can. But my question is: could we use it as IntegrationName. From manifest file we can get "`Snyk Vulnerability Scanner (Preview)`" string. But IntegrationName more related to IDE name. This value used for Snyk CLI `SNYK_INTEGRATION_NAME`. As I remember for `SNYK_INTEGRATION_NAME` we use something like INTELLIJ, VISUAL_STUDIO, PYTHON etc.

2021-10-04 08:13 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykExtension.cs
> +        public const string IntegrationName = "VISUAL_STUDIO_PREVIEW";
Get method can transform manifest name into CLI-required name:
1. Drop brackets
0. Replace spaces with underscores.

2021-10-04 12:17 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykExtension.cs
> +        public const string IntegrationName = "VISUAL_STUDIO_PREVIEW";
My bad, misinterpreted it. How about leaving it as-is as "VISUAL_STUDIO"?

2021-10-04 13:15 UTC, aldanchenko commented on Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykExtension.cs
> +        public const string IntegrationName = "VISUAL_STUDIO_PREVIEW";
@michelkaporin fixed integration name :)

2021-10-04 13:21 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
Should we have two manifest files next to each other for the meantime?

2021-10-04 13:27 UTC, aldanchenko commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
I don't sure. This changes in dev branch, separated from main branch. As I understand you suggest to have two preview manifest files? Could you please clarify what will be in each file?

2021-10-04 14:06 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
> This changes in dev branch, separated from main branch. 

What happens when Snyk Code branch will be merged into master? We'll overwrite the stable version manifest, right? This poses a question how should we maintain manifest for different extension types.

Therefore, I am suggesting to have two files next to each other, namely:
- `source.extension.vsixmanifest`
- `source.extension.preview.vsixmanifest`
One will be used for stable released, another for preview release.

2021-10-04 15:31 UTC, aldanchenko commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
I can make it, but I'm still don't see the need for it now. As I understand we will need second file only once - when we will move `snykcode-dev` branch to `main` branch. We could just change `source.extension.vsixmanifest` before merge to `main`. We will still need to update `source.extension.vsixmanifest` in `main`. As I understand if we will make two manifest files, we will need to support both files. It seems to me that it will only double the work. 

Please don't misunderstand me. I don't mind. I just don't understand what the plus is 🤔

2021-10-04 15:35 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
Let me ask you the question - how do we plan to release "Preview" versions of the extension after Snyk Code lands in `main`?

2021-10-04 15:37 UTC, aldanchenko commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
Good question! Because I didn't think that we will have some other "Preview" versions 🙃

2021-10-04 15:43 UTC, aldanchenko commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
Thanks @michelkaporin! Now I understand your idea! 👍 Added `source.extension.preview.vsixmanifest`

2021-10-04 15:53 UTC, michelkaporin commented on Snyk.VisualStudio.Extension/source.extension.vsixmanifest
>  ﻿<?xml version="1.0" encoding="utf-8"?>
👍 Maybe there's a better way to do it than having two files but we can always explore and streamline the process in future :)

2021-10-04 16:23 UTC, aldanchenko commented
@michelkaporin thanks. Fixed the build.

2021-10-04 19:13 UTC, michelkaporin commented on .github/workflows/build.yml
> +name: nightly-build
why is it called nightly if we don't run it nightly?

2021-10-04 19:13 UTC, michelkaporin commented on .github/workflows/build.yml
> +  DEFAULT_BRANCH: feat/snykcode-dev
why was it different previously? 🤔

2021-10-05 08:16 UTC, aldanchenko commented on .github/workflows/build.yml
> +name: nightly-build
This name was given at the very beginning. Maybe because it sounds beautiful :)

2021-10-05 08:19 UTC, aldanchenko commented on .github/workflows/build.yml
> +  DEFAULT_BRANCH: feat/snykcode-dev
Because we had such a brunch at the very beginning and after that it didn't changed. Although we don't use it now. 

@michelkaporin this is an important point, but maybe we won't stretch the PR review?

2021-10-05 08:52 UTC, michelkaporin commented on .github/workflows/build.yml
> +  DEFAULT_BRANCH: feat/snykcode-dev
sure, let's not stretch this PR but in that case link the ticket and we're done with this PR ✔️

2021-10-05 13:29 UTC, aldanchenko commented on .github/workflows/build.yml
> +  DEFAULT_BRANCH: feat/snykcode-dev
Added new ticket to Jira :)

2021-10-05 15:41 UTC, michelkaporin approved these changes
LGTM ✅

2021-10-05 16:24 UTC, aldanchenko commented
Thanks @michelkaporin!

2021-10-05 16:24 UTC, merged