[ROAD-682] fix: add check is sentry error related to extension
snyk/snyk-visual-studio-plugin pull request #85
Opened 2022-01-31 15:09 UTC by aldanchenko

To fix issue with not related to extension exceptions now it filter Sentry errors before send. It check Logger property and StackTrace content. 

Errors from extension must have SentryEvent.Logger = "Snyk.VisualStudio.CLI.SomeClass" property set. And also error must have Snyk mention in StackTrace

2022-01-31 18:00 UTC, michelkaporin requested changes
Let's work with Sentry integrations instead, as discussed during the call today 👌

2022-02-03 08:40 UTC, bastiandoetsch commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +            => e != null && e.StackTrace != null && e.StackTrace.Contains(SnykKey);
Maybe it would be good to be case-insensitive here, so we catch everything Snyk, and not only the capitalized parts.

2022-02-03 08:42 UTC, bastiandoetsch approved these changes
Please consider to do case-insensitive handling. Apart from that, LGTM.

2022-02-03 08:42 UTC, michelkaporin commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +            => e != null && e.StackTrace != null && e.StackTrace.Contains(SnykKey);
Does stacktrace include path to the extension? Perhaps we can be more precise and say the path has to be within the stacktrace, instead just "Snyk" string?

2022-02-03 08:50 UTC, michelkaporin commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +        protected static bool IsNeedToHandleException(Exception e)
Does this work when AggregateException with N-layers of InnerException comes?

2022-02-03 08:53 UTC, aldanchenko commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +            => e != null && e.StackTrace != null && e.StackTrace.Contains(SnykKey);
Discussed in Slack. Decided to leave as is right now.

2022-02-03 08:59 UTC, aldanchenko commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +        protected static bool IsNeedToHandleException(Exception e)
Good point @michelkaporin!

2022-02-03 09:00 UTC, aldanchenko commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +        protected static bool IsNeedToHandleException(Exception e)
@michelkaporin changed this part according to your comment. Please, have a look ;)

2022-02-03 09:08 UTC, michelkaporin commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +        protected static bool IsNeedToHandleException(Exception e)
Looks good. Consider using Linq to simplify this simple foreach :)

2022-02-03 09:20 UTC, aldanchenko commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +        protected static bool IsNeedToHandleException(Exception e)
```
protected static bool IsNeedToHandleException(Exception e)
        {
            if (IsExceptionRelatedToExtension(e))
            {
                return true;
            }

            if (e is AggregateException aggregateException 
                && aggregateException.Flatten().InnerExceptions.Where(ex => IsExceptionRelatedToExtension(ex)).IsNullOrEmpty())
            {
                return true;
            }

            return false;
        }
```

2022-02-03 09:21 UTC, aldanchenko commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +        protected static bool IsNeedToHandleException(Exception e)
@michelkaporin this will be ok?

2022-02-03 10:56 UTC, michelkaporin commented on Snyk.Common/Sentry/AbstractIntegration.cs
> +        protected static bool IsNeedToHandleException(Exception e)
You can work with .Any() to have it simpler 👍

2022-02-03 10:56 UTC, michelkaporin approved these changes

2022-02-03 11:54 UTC, merged